name: vector-r
version: 0.1.0
homepage: https://github.com/morloclib/vector-r
synopsis: R implementations for the vector module
description: Base R implementations of the Nat-parameterised dense 1D vector primitives.
category: data
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/vector-r
bug-reports: https://github.com/morloclib/vector-r
